# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: '2'
services:

  node-chrome:
    image: selenium/node-chrome:3.11.0-bismuth
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "5901:5900"

  node-chrome-debug:
    image: selenium/node-chrome-debug:3.11.0-bismuth
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "5902:5900"

  node-firefox-debug:
    image: selenium/node-firefox-debug:3.11.0-bismuth
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    ports:
      - "5903:5900"

  hub:
    image: selenium/hub:3.11.0-bismuth
    environment:
      GRID_BROWSER_TIMEOUT: 10000 # 10 seconds
      GRID_TIMEOUT: 10000
    ports:
      - "4444:4444"
